#!/usr/bin/env bash
# Install nginx on your web-01 server that listen on port 80

apt-get update
apt-get install -y nginx

# Create default page
echo "Hello World!" > /var/www/html/index.html

# Configurate server
ufw allow 'Nginx HTTP'

service nginx restart
